name = "Vindicta"
prefix = "vindicta"
author = "Vindicta Team"
template = "cba"
mainprefix = "z"
include = ["./include"]
files = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_vindicta.paa"
]
folder_optionals = true
sig_version = 3
reuse_private_key = true
